tectracking/inventory/urls.py
from django.conf.urls.defaults import patterns, url
from tectracking.inventory.views import InventoryListView

urlpatterns = patterns(
    '',
    url(r'^$', InventoryListView.as_view(), name='inventory'),
)

tectracking/reporting/urls.py
from django.conf.urls.defaults import patterns, url
from django.views.generic.base import RedirectView
from tectracking.reporting.views import ActivityReportingView, InventoryReportingView, TaskReportingView
from tectracking.utils import reverse_lazy

urlpatterns = patterns(
    '',
    url(r'^$', RedirectView.as_view(url=reverse_lazy('reporting_activity')), name='reporting'),
    url(r'^activities/$', ActivityReportingView.as_view(), name='reporting_activity'),
    url(r'^tasks/$', TaskReportingView.as_view(), name='reporting_tasks'),
    url(r'^inventory/$', InventoryReportingView.as_view(), name='reporting_inventory'),
)

tectracking/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib.auth.views import login, logout, password_reset, password_reset_complete, \
    password_reset_confirm, password_reset_done
from django.views.generic.base import RedirectView
from tectracking.common.views import IndexView, RegisterView, RegisterCompleteView
from tectracking.utils import reverse_lazy

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', RedirectView.as_view(url=reverse_lazy('index')), name='root'),
    url(r'^index/$', IndexView.as_view(), name='index'),
    url(r'^activities/', include('tectracking.activities.urls')),
    url(r'^inventory/', include('tectracking.inventory.urls')),
    url(r'^reporting/', include('tectracking.reporting.urls')),
    url(r'^auth/login/$', login, {'template_name': 'auth/login.html'}),
    url(r'^auth/logout/$', logout, {'next_page': reverse_lazy('index')}),
    url(r'^auth/register/$', RegisterView.as_view(), name='register'),
    url(r'^auth/register/complete/$', RegisterCompleteView.as_view(), name='register_complete'),
    url(r'^auth/reset/$', password_reset, {'template_name': 'auth/password_reset.html',
                                           'email_template_name': 'auth/password_reset_email.html'}),
    url(r'^auth/reset/done/$', password_reset_done, {'template_name': 'auth/password_reset_done.html'}),
    url(r'^auth/reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm,
                                                    {'template_name': 'auth/password_reset_confirm.html'}),
    url(r'^auth/reset/complete/$', password_reset_complete,
                                                    {'template_name': 'auth/password_reset_complete.html'}),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),
)

tectracking/activities/models.py
from django.db import models
from django.contrib.auth.models import User

class Activity(models.Model):
    REQUIRED_CHOICES = (
        (u'Y', u'Yes'),
        (u'N', u'No'),
    )

    STATUS_CHOICES = (
        (u'N', u'Not Accepted'),
        (u'A', u'Accepted'),
        (u'I', u'Incomplete'),
        (u'C', u'Complete'),
    )

    tec_id = models.CharField(max_length=11, primary_key=True)
    approved_id = models.CharField(max_length=11, blank=True, null=True)
    event_type = models.CharField(max_length=10)
    short_desc = models.CharField(max_length=60, verbose_name='short description')
    reservation_desc = models.CharField(max_length=300, verbose_name='reservation description')
    tec_site = models.CharField(max_length=60)
    event_location = models.CharField(max_length=60)
    event_start_date = models.DateField()
    event_end_date = models.DateField()
    event_organizer = models.CharField(max_length=60)
    date_entered = models.DateField()
    date_last_mod = models.DateField(null=True, blank=True, verbose_name='date last modified')
    event_size = models.IntegerField(null=True, blank=True)
    sponsor_mgr = models.CharField(max_length=60, null=True, blank=True, verbose_name='sponsor manager')
    class_mgr = models.CharField(max_length=60, verbose_name='class manager')
    siebel_num = models.CharField(max_length=9, null=True, blank=True, db_column='siebel_no', verbose_name='siebel number')
    num_attendees = models.IntegerField(db_column='no_attendees', verbose_name='number of attendees')
    room_required = models.CharField(max_length=1, choices=REQUIRED_CHOICES)
    laptops_required = models.CharField(max_length=1, choices=REQUIRED_CHOICES)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='N')

    reserved_assets = models.ManyToManyField('inventory.Asset', through='inventory.AssetReservation')
    tasks = models.ManyToManyField('Task', through='ActivityTask')

    class Meta:
        db_table = 'tracking_source'
        verbose_name_plural = 'activities'
        ordering = ['-event_start_date', '-event_end_date']
        permissions = (
            ('can_approve_activity', 'Can approve an activity by settings its approved id'),
            ('can_accept_activity', 'Can accept an activity by settings its status to accepted'),
            ('can_close_activity', 'Can close an activity by settings its status to complete'),
        )

    def __unicode__(self):
        return self.tec_id

class Task(models.Model):
    task_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, unique=True)

    class Meta:
        db_table = 'task'

    def __unicode__(self):
        return self.name

class ActivityTask(models.Model):
    activity = models.ForeignKey(Activity, db_column='tec_id')
    task = models.ForeignKey(Task)
    status = models.CharField(max_length=300, null=True, blank=True)
    assigned_user = models.ForeignKey(User, db_column='auth_user_id', null=True, blank=True, verbose_name='assigned to')

    class Meta:
        db_table = 'activity_tasks'
        permissions = (
            ('can_change_task_status', 'Can change the status of a task'),
            ('can_assign_task', 'Can assign a task to a user'),
        )

    def __unicode__(self):
        return '%s | %s' % (self.activity.tec_id, self.task.name)

class Assignment(models.Model):
    PRIORITY_CHOICES = (
        (1, u'High Priority'),
        (2, u'Normal Priority'),
        (3, u'Low Priority'),
    )

    activity = models.OneToOneField(Activity, db_column='tec_id')
    user = models.ForeignKey(User, db_column='auth_user_id')
    priority = models.SmallIntegerField(choices=PRIORITY_CHOICES, default=2)
    escalation_status = models.CharField(max_length=300, null=True, blank=True)

    class Meta:
        db_table = 'activity_assignments'
        ordering = ['priority']

    def __unicode__(self):
        return '%s | %s' % (self.activity.tec_id, self.user.get_full_name())

class Note(models.Model):
    note_id = models.AutoField(primary_key=True)
    activity = models.ForeignKey(Activity, db_column='tec_id')
    user = models.ForeignKey(User, db_column='auth_user_id')
    message = models.TextField()

    class Meta:
        db_table = 'activity_note'

    def __unicode__(self):
        return '%s | %s' % (self.activity.tec_id, self.user.get_full_name())

tectracking/inventory/models.py
from django.db import models

class Asset(models.Model):
    serial_num = models.CharField(max_length=8, primary_key=True, db_column='serial_no', verbose_name='serial number')
    bar_code = models.IntegerField(unique=True, db_column='bar_code_id')
    rfid = models.IntegerField(null=True, blank=True)
    asset_model_mfg = models.CharField(max_length=10, verbose_name='model manufacturer')
    asset_model_type = models.CharField(max_length=15, verbose_name='model type')
    asset_model_name = models.CharField(max_length=8, verbose_name='model name')
    amt_memory = models.SmallIntegerField(null=True, blank=True, verbose_name='amount memory')
    num_cores = models.SmallIntegerField(null=True, blank=True, db_column='no_cores', verbose_name='number of cores')

    categories = models.ManyToManyField('Category', through='AssetCategory')

    class Meta:
        db_table = 'inventory_source'

    def __unicode__(self):
        return self.serial_num

class Category(models.Model):
    category_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, unique=True, verbose_name='category')

    class Meta:
        db_table = 'asset_category'
        verbose_name_plural = 'categories'

    def __unicode__(self):
        return self.name

class AssetCategory(models.Model):
    asset = models.ForeignKey(Asset, db_column='serial_no')
    category = models.ForeignKey(Category, db_column='category_id',)

    class Meta:
        db_table = 'asset_categories'
        verbose_name_plural = 'asset categories'

    def __unicode__(self):
        return '%s | %s' % (self.asset.serial_num, self.category.name)

class Note(models.Model):
    note_id = models.AutoField(primary_key=True)
    asset = models.ForeignKey(Asset, db_column='serial_no')
    message = models.TextField()

    class Meta:
        db_table = 'asset_note'

class Room(models.Model):
    asset = models.OneToOneField(Asset, db_column='serial_no')
    location = models.CharField(max_length=300)
    capacity = models.IntegerField()
    num_workstations = models.IntegerField(null=True, blank=True, db_column='no_workstations', verbose_name='number of worksations')

    class Meta:
        db_table = 'room'

    def __unicode__(self):
        return self.location

class AssetReservation(models.Model):
    activity = models.ForeignKey('activities.Activity', db_column='tec_id')
    asset = models.ForeignKey(Asset, db_column='serial_no')
    datetime = models.DateTimeField(verbose_name='time')
    duration = models.TimeField()

    class Meta:
        db_table = 'asset_reservations'
        ordering = ['-datetime', '-duration']

    def __unicode__(self):
        return '%s | %s' % (self.activity.tec_id, self.room.location)

tectracking/reporting/models.py
from django.db import models

# Create your models here.

tectracking/inventory/views.py
from models import Asset, AssetCategory, Note
from django.contrib.auth.models import User
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.utils.datastructures import DotExpandedDict
from django.core.exceptions import ValidationError
from django.http import HttpResponseRedirect

class InventoryListView(ListView):
    model = Asset

    def get_context_data(self, **kwargs):
	disp_inventory = Asset.objects.filter()

        context = {
            'disp_inventory': disp_inventory,
        }
        kwargs.update(context)
        return super(InventoryListView, self).get_context_data(**kwargs)

tectracking/reporting/views.py
from tectracking.activities.models import Activity, ActivityTask
from tectracking.inventory.models import Asset
from django.views.generic.list import ListView

class ActivityReportingView(ListView):
    model = Activity
    template_name = 'reporting/activities.html'

class TaskReportingView(ListView):
    model = ActivityTask
    template_name = 'reporting/tasks.html'

class InventoryReportingView(ListView):
    model = Asset
    template_name = 'reporting/inventory.html'

tectracking/reporting/templates/reporting/activities.html
{% extends "base.html" %}
{% load url from future %}

{% block title %}{{ block.super }} | Activities Report{% endblock %}

{% block content %}
<div class="content_block">
<div class="content_head">
  <div id="report_header_left" >
    <ul>
      <li ><a class="linkbutton" href="{% url 'reporting_activity' %}">Activities Report</a></li>
</ul>
</div>
  <div id="report_header_right">
    <ul>
      <li ><a class="linkbutton" href="{% url 'reporting_tasks' %}">Tasks Report</a></li>
    </ul>
  </div>
  <h2>Activities Report</h2>
</div>
<table id="activity_report">
	<thead>
	<tr>
		<th><div>TEC ID</div></th>
		<th><div>Approved ID</div></th>
		<th><div>Event Type</div></th>
		<th><div>Event Title</div></th>
		<th><div>Reservation Description</div></th>
		<th><div>TEC Site</div></th>
		<th><div>Event Location</div></th>
		<th><div>Event Start Date</div></th>
		<th><div>Event End Date</div></th>
		<th><div>Event Organizer</div></th>
		<th><div>Date Entered</div></th>
		<th><div>Last Modified</div></th>
		<th><div>Event Size</div></th>
		<th><div>Sponsor Manager</div></th>
		<th><div>Class Manager</div></th>
		<th><div>Siebel Number</div></th>
		<th><div>Number of Attendees</div></th>
		<th><div>Room Required</div></th>
		<th><div>Laptops Required</div></th>
		<th><div>Status</div></th>
		<th><div>Assigned To</div></th>
		<th><div>Priority</div></th>
		<th><div>Escalation Status</div></th>
	</tr>
	</thead>
	<tbody>
	{% for activity in activity_list %}
	<tr class="{% cycle 'row_one' 'row_two' %}">
		<td><a href="{% url 'activity_detail' activity.tec_id %}"><span class="ui-icon ui-icon-search"></span>{{ activity.tec_id }}</a></td>
		<td>{{ activity.approved_id|default:'Not Approved' }}</td>
		<td>{{ activity.event_type }}</td>
		<td>{{ activity.short_desc }}</td>
		<td>{{ activity.reservation_desc }}</td>
		<td>{{ activity.tec_site }}</td>
		<td>{{ activity.event_location }}</td>
		<td>{{ activity.event_start_date }}</td>
		<td>{{ activity.event_end_date }}</td>
		<td>{{ activity.event_organizer }}</td>
		<td>{{ activity.date_entered }}</td>
		<td>{{ activity.date_last_mod|default:'Not Provided' }}</td>
		<td>{{ activity.event_size|default:'Not Provided' }}</td>
		<td>{{ activity.sponsor_mgr|default:'Not Provided' }}</td>
		<td>{{ activity.class_mgr|default:'Not Provided' }}</td>
		<td>{{ activity.siebel_num|default:'Not Provided' }}</td>
		<td>{{ activity.num_attendees }}</td>
		<td>{{ activity.get_room_required_display }}</td>
		<td>{{ activity.get_laptops_required_display }}</td>
		<td>{{ activity.get_status_display }}</td>
		<td>{{ activity.assignment.user.get_full_name }}</td>
		<td>{{ activity.assignment.get_priority_display }}</td>
		<td>{{ activity.assignment.escalation_status }}</td>
	</tr>
	{% endfor %}
	</tbody>
</table>
<div class="clearfix"></div>
</div>
{% endblock %}

{% block scripts %}
<script type='text/javascript'>
    $(document).ready(function() {
        $('#activity_report').dataTable({
            "bJQueryUI": true,
            "sPaginationType": "full_numbers",
            "oLanguage": {
                "sSearch": "Search all columns:"
            },
            "sDom": 'CT<"clear">lfrtip',
            "oTableTools": {
                "sSwfPath": "{{ STATIC_PREFIX }}swf/copy_cvs_xls_pdf.swf"
            }
        });

        $('.ColVis_Button').button();

        $('.dataTables_filter').after($('<div id="table_wrapper"></div>'));
        $('#table_wrapper').append($('#activity_report'));
    });
</script>
{% endblock %}

tectracking/reporting/templates/reporting/inventory.html
{% extends "base.html" %}

tectracking/reporting/templates/reporting/tasks.html
{% extends "base.html" %}
{% load url from future %}

{% block title %}{{ block.super }} | Tasks Report{% endblock %}

{% block content %}
<div class="content_block">
<div class="content_head">
  <div id="report_header_left" >
    <ul>
      <li><a class="linkbutton" href="{% url 'reporting_activity' %}">Activities Report</a></li>
</ul>
</div>
  <div id="report_header_right">
    <ul>
      <li><a class="linkbutton" href="{% url 'reporting_tasks' %}">Tasks Report</a></li>
    </ul>
  </div>
  <h2>Tasks Report</h2>
</div>
<table id="tasks_report">
    <thead>
    <tr>
        <th><div>Activity TEC ID</div></th>
        <th><div>Task Name</div></th>
        <th><div>Task Assigned To</div></th>
        <th><div>Task Status</div></th>
        <th><div>Acitivity Approved ID</div></th>
        <th><div>Acitivty Event Type</div></th>
        <th><div>Activity Event Title</div></th>
        <th><div>Activity Event Start Date</div></th>
        <th><div>Activity Event End Date</div></th>
        <th><div>Acitivity Siebel Number</div></th>
        <th><div>Acitivity Status</div></th>
        <th><div>Activity Assigned To</div></th>
        <th><div>Activity Priority</div></th>
    </tr>
    </thead>
    <tbody>
    {% for activity_task in activitytask_list %}
    <tr class="{% cycle 'row_one' 'row_two' %}">
        <td><a href="{% url 'activity_detail' activity_task.activity.tec_id %}"><span class="ui-icon ui-icon-search"></span>{{ activity_task.activity.tec_id }}</a></td>
        <td>{{ activity_task.task.name }}</td>
        <td>{{ activity_task.assigned_user.get_full_name }}</td>
        <td>{{ activity_task.status }}</td>
        <td>{{ activity_task.activity.approved_id|default:'Not Approved' }}</td>
        <td>{{ activity_task.activity.event_type }}</td>
        <td>{{ activity_task.activity.short_desc }}</td>
        <td>{{ activity_task.activity.event_start_date }}</td>
        <td>{{ activity_task.activity.event_end_date }}</td>
        <td>{{ activity_task.activity.siebel_num|default:'Not Provided' }}</td>
        <td>{{ activity_task.activity.get_status_display }}</td>
        <td>{{ activity_task.activity.assignment.user.get_full_name }}</td>
        <td>{{ activity_task.activity.assignment.get_priority_display }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
</div>
{% endblock %}

{% block scripts %}
<script type='text/javascript'>
    $(document).ready(function() {
        $('#tasks_report').dataTable({
            "bJQueryUI": true,
            "sPaginationType": "full_numbers",
            "oLanguage": {
                "sSearch": "Search all columns:"
            },
            "sDom": 'CT<"clear">lfrtip',
            "oTableTools": {
                "sSwfPath": "{{ STATIC_PREFIX }}swf/copy_cvs_xls_pdf.swf"
            }
        });

        $('.ColVis_Button').button();

        $('.dataTables_filter').after($('<div id="table_wrapper"></div>'));
        $('#table_wrapper').append($('#tasks_report'));
    });
</script>
{% endblock %}